#!/usr/bin/env node
'use strict'

const meow = require('meow')
const duo = require('./')

const cli = meow(`
    Usage
      duo  <command> [<hue> <hue>]
  
    Commands
      check              Check the contrast between the main two colors generated by two hues
      gen                Generate a duotone theme. If one or the two hues are omited it automatically generate  the rest

    Options
      --name, -n         The name of your theme. (Default: '')
      --minimum, -m      The minimum contrast to validate when checking. (Default: 'AA')

    Examples
      duo gen
      duo gen 22
      duo gen 22 300
      duo gen 22 300 --name duotone-awesome-theme

      duo check 22 300
      duo check 22 300 -m AAA

`, {
  alias: {
    n: 'name',
    m: 'minimum'
  }
})

if (cli.input.length === 0) {
  cli.showHelp()
  process.exit(0)
}

if (cli.input[0] === 'gen') {
  const colors = cli.input.slice(1)
  duo.gen.apply(null, colors)
}

if (cli.input[0] === 'check') {
  const colors = cli.input.slice(1)
  duo.check.apply(null, colors)
}
